#!/usr/bin/env bash
# Copyright (c) 2026 Ronen Druker.
# build-foomatic-rip.sh — cross-compile foomatic-rip 4.0.17 for aarch64.
#
# Rationale: cups-filters 1.0.37 does NOT ship foomatic-rip (it was folded
# in only in cups-filters 1.28+). Foo2zjs PPDs generated by Foomatic
# embed a *FoomaticRIPCommandLine directive that requires foomatic-rip
# to translate into a real driver invocation. Without it, CUPS errors with
# "File /usr/lib/cups/filter/foomatic-rip not available".
#
# This script fetches foomatic-filters 4.0.17 (the last standalone release,
# sibling of foomatic-db-engine at that version), cross-compiles the
# foomatic-rip binary against the SDK toolchain, and packages it as a
# tar.gz that install-foomatic-rip.sh unpacks at /usr/lib/cups/filter/.
#
# Output: /host/output/foomatic-rip-aarch64.tar.gz
set -euo pipefail

CONTAINER=openwrt-build
FR_URL="https://www.openprinting.org/download/foomatic/foomatic-filters-4.0.17.tar.gz"
FR_VER="4.0.17"

docker exec -u builder "$CONTAINER" bash -c "
  set -euo pipefail

  WORK=/workspace/foomatic-rip-build
  mkdir -p \$WORK
  cd \$WORK

  if [ ! -f foomatic-filters-${FR_VER}.tar.gz ]; then
    echo '[foomatic-rip] Downloading…'
    curl -fL --retry 3 -o foomatic-filters-${FR_VER}.tar.gz '$FR_URL'
  fi

  if [ ! -d foomatic-filters-${FR_VER} ]; then
    echo '[foomatic-rip] Extracting…'
    tar -xzf foomatic-filters-${FR_VER}.tar.gz
  fi

  cd foomatic-filters-${FR_VER}

  # SDK toolchain (same approach as build-foo2zjs.sh).
  STAGING=/workspace/sdk/staging_dir
  TOOLCHAIN=\$(ls -d \$STAGING/toolchain-aarch64_cortex-a53_gcc-*_musl | head -1)
  CROSS=\$TOOLCHAIN/bin/aarch64-openwrt-linux-musl-
  export CC=\${CROSS}gcc
  export STRIP=\${CROSS}strip
  # -fcommon: foomatic-rip 4.0.17 declares global vars (cupsfilter,
  #   postpipe, printer_model) as tentative definitions in a shared
  #   header without extern — works under GCC <10's default -fcommon
  #   but fails with GCC 10+'s -fno-common default (multiple definition).
  #   Patching each .c/.h is more invasive than reverting the default.
  export CFLAGS=\"-Os -pipe -mcpu=cortex-a53 -fcommon --sysroot=\$TOOLCHAIN\"
  export LDFLAGS=\"--sysroot=\$TOOLCHAIN\"

  # Autotools cross-compile: --host sets the target triplet so configure
  # uses cross tools; --build is detected from the Ubuntu x86_64 container.
  #
  # --disable-dbus: avoids colord/dbus-1 dep (no dbus on our router CUPS).
  # NOCONVERTERCHECK=1: skip autoconf's file-converter hunt at configure
  #   time — texttops/a2ps/enscript/mpage are not in the SDK staging dir
  #   but ARE on the router (texttops ships with cups-filters runtime).
  #   Foomatic-rip only needs these when printing text jobs, and the path
  #   search happens at runtime.
  # Always re-run configure if Makefile wasn't produced for aarch64.
  # ac_cv_func_malloc/realloc_0_nonnull=yes: autoconf's AC_FUNC_MALLOC test
  #   can't run under cross-compile, so by default it assumes malloc(0)
  #   returns NULL (\"broken\") and substitutes rpl_malloc/rpl_realloc —
  #   symbols that don't exist anywhere, causing link failure. musl's
  #   malloc(0) returns non-NULL, so force the yes path.
  if [ ! -f Makefile ] || ! grep -q aarch64 Makefile; then
    echo '[foomatic-rip] Configuring (cross-compile)…'
    NOCONVERTERCHECK=1 \
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes \
    ./configure \
      --host=aarch64-openwrt-linux-musl \
      --prefix=/usr \
      --disable-dbus 2>&1 | tail -20
  fi

  echo '[foomatic-rip] Building…'
  make -j2 foomatic-rip 2>&1 | tail -20

  # Verify the binary is aarch64
  file foomatic-rip

  # Stage install tree
  STAGE=/workspace/foomatic-rip-build/stage
  rm -rf \$STAGE
  mkdir -p \$STAGE/usr/lib/cups/filter
  mkdir -p \$STAGE/etc/cups

  cp foomatic-rip \$STAGE/usr/lib/cups/filter/
  chmod 755 \$STAGE/usr/lib/cups/filter/foomatic-rip

  # Minimal filter.conf so foomatic-rip can locate logs/tempdir.
  cp filter.conf \$STAGE/etc/cups/foomatic-rip.conf

  \$STRIP \$STAGE/usr/lib/cups/filter/foomatic-rip

  cd \$STAGE
  tar -czf /host/output/foomatic-rip-aarch64.tar.gz .
  ls -la /host/output/foomatic-rip-aarch64.tar.gz
  echo '[foomatic-rip] Contents:'
  tar -tzf /host/output/foomatic-rip-aarch64.tar.gz
"
