#!/usr/bin/env bash
# Copyright (c) 2026 Ronen Druker.
# build-foo2zjs.sh — cross-compile foo2zjs for aarch64-openwrt using the
# SDK toolchain, without wrapping it in a full OpenWrt .ipk package.
#
# Rationale: foo2zjs's upstream Makefile is hand-rolled and installs a large
# set of PPDs, firmware loaders (Python getweb), and wrapper scripts we
# don't need. Writing a proper OpenWrt Package/* define for all of that is
# more work than the benefit (opkg metadata). For the HP LaserJet 1022
# specifically we only need:
#   - foo2zjs binary              — converts CUPS raster to ZjStream
#   - foo2zjs-wrapper script      — invoked by CUPS as a filter
#   - HP-LaserJet_1022*.ppd       — PPD file for lpadmin
#
# We build the binary against the SDK's aarch64 toolchain, grab the
# wrapper + PPD from the source tree as-is, and stage them in a tar.gz
# that install-foo2zjs.sh unpacks on the router.
#
# Output: /host/output/foo2zjs-hp-lj1022.tar.gz
set -euo pipefail

CONTAINER=openwrt-build
FOO2ZJS_URL="https://github.com/OpenPrinting/foo2zjs/archive/refs/tags/upstream/20200505.tar.gz"
FOO2ZJS_VER="20200505"

docker exec -u builder "$CONTAINER" bash -c "
  set -euo pipefail

  WORK=/workspace/foo2zjs-build
  mkdir -p \$WORK
  cd \$WORK

  if [ ! -f foo2zjs-${FOO2ZJS_VER}.tar.gz ]; then
    echo '[foo2zjs] Downloading…'
    curl -fL --retry 3 -o foo2zjs-${FOO2ZJS_VER}.tar.gz '$FOO2ZJS_URL'
  fi

  if [ ! -d src ]; then
    echo '[foo2zjs] Extracting…'
    mkdir -p src
    tar -xzf foo2zjs-${FOO2ZJS_VER}.tar.gz -C src --strip-components=1
  fi

  cd src

  # Set SDK toolchain env — same vars OpenWrt's rules.mk exports for packages.
  STAGING=/workspace/sdk/staging_dir
  TOOLCHAIN=\$(ls -d \$STAGING/toolchain-aarch64_cortex-a53_gcc-*_musl | head -1)
  TARGET_DIR=\$(ls -d \$STAGING/target-aarch64_cortex-a53_musl | head -1)
  CROSS=\$TOOLCHAIN/bin/aarch64-openwrt-linux-musl-
  export CC=\${CROSS}gcc
  export AR=\${CROSS}ar
  export STRIP=\${CROSS}strip
  export CFLAGS=\"-Os -pipe -mcpu=cortex-a53 --sysroot=\$TOOLCHAIN\"
  export LDFLAGS=\"--sysroot=\$TOOLCHAIN\"

  echo \"[foo2zjs] Toolchain: \$CC\"
  \$CC --version | head -1

  # foo2zjs's Makefile respects CC/CFLAGS/LDFLAGS but hardcodes 'gcc' in a
  # couple of places — patch if needed. First try a direct build.
  make clean >/dev/null 2>&1 || true
  echo '[foo2zjs] Building foo2zjs binary + wrapper…'
  # foo2zjs: aarch64 ELF (cross-compiled).
  # foo2zjs-wrapper: shell script generated by sed-substitution in the
  #   Makefile — no compilation, safe to build with host tools.
  make foo2zjs CC=\"\$CC\" CFLAGS=\"\$CFLAGS\" LDFLAGS=\"\$LDFLAGS\" 2>&1 | tail -20
  make foo2zjs-wrapper 2>&1 | tail -5

  # Verify the binary is aarch64
  file foo2zjs
  test -f foo2zjs-wrapper || { echo '[foo2zjs] ERROR: wrapper not generated'; exit 1; }

  # Stage install tree
  STAGE=/workspace/foo2zjs-build/stage
  rm -rf \$STAGE
  mkdir -p \$STAGE/usr/lib/cups/filter
  mkdir -p \$STAGE/usr/share/cups/model
  mkdir -p \$STAGE/usr/share/foomatic/db/source/opt

  # Binary + wrapper
  cp foo2zjs             \$STAGE/usr/lib/cups/filter/
  cp foo2zjs-wrapper     \$STAGE/usr/lib/cups/filter/
  chmod 755 \$STAGE/usr/lib/cups/filter/foo2zjs \$STAGE/usr/lib/cups/filter/foo2zjs-wrapper

  # PPD for HP LaserJet 1022 — lives under PPD/ in upstream source.
  cp PPD/HP-LaserJet_1022.ppd \$STAGE/usr/share/cups/model/

  # Strip binary to save space on flash
  \$STRIP \$STAGE/usr/lib/cups/filter/foo2zjs

  # Package as tarball
  cd \$STAGE
  tar -czf /host/output/foo2zjs-hp-lj1022.tar.gz .
  ls -la /host/output/foo2zjs-hp-lj1022.tar.gz
  echo '[foo2zjs] Contents:'
  tar -tzf /host/output/foo2zjs-hp-lj1022.tar.gz
"
